path : /mnt/gpu_storage/traffic-sign-detection/TSD/datasets/
train: sliced/train/images/
val  : sliced/val/images/

# class names
names: 
  0 : warning
  1 : other
  2 : information
  3 : regulatory
  4 : complementary
