path :
train: /mnt/gpu_storage/traffic-sign-detection/datasets/default_MTSD/train/
val  : /mnt/gpu_storage/traffic-sign-detection/datasets/default_MTSD/val/
test : /mnt/gpu_storage/traffic-sign-detection/datasets/default_MTSD/test/

# class names
names: 
  0: 'traffic_sign'