path : /mnt/gpu_storage/traffic-sign-detection/TSD/datasets/
train: default_MTSD/train/images/
val  : default_MTSD/val/images/
test : default_MTSD/test/images/

# class names
names: 
  0: 'information--limited-access-road--g1' 
  1: 'regulatory--bicycles-only--g1' 
  2: 'regulatory--no-heavy-goods-vehicles--g2' 
  3: 'other-sign' 
  4: 'regulatory--keep-right--g1' 
  5: 'regulatory--no-stopping--g15' 
  6: 'warning--traffic-merges-right--g1' 
  7: 'complementary--obstacle-delineator--g2' 
  8: 'warning--roundabout--g25' 
  9: 'warning--domestic-animals--g1' 
  10: 'warning--road-widens--g1' 
  11: 'regulatory--maximum-speed-limit-45--g3' 
  12: 'warning--kangaloo-crossing--g1' 
  13: 'warning--junction-with-a-side-road-perpendicular-left--g3' 
  14: 'regulatory--no-bicycles--g1' 
  15: 'regulatory--give-way-to-oncoming-traffic--g1' 
  16: 'information--parking--g3' 
  17: 'regulatory--stop--g1' 
  18: 'warning--railroad-crossing-without-barriers--g1' 
  19: 'warning--railroad-crossing--g4' 
  20: 'warning--crossroads-with-priority-to-the-right--g1' 
  21: 'information--pedestrians-crossing--g2' 
  22: 'warning--roadworks--g4' 
  23: 'regulatory--maximum-speed-limit-30--g1' 
  24: 'information--airport--g2' 
  25: 'warning--junction-with-a-side-road-acute-right--g1' 
  26: 'regulatory--maximum-speed-limit-80--g1' 
  27: 'warning--roadworks--g2' 
  28: 'regulatory--keep-right--g6' 
  29: 'regulatory--priority-road--g4' 
  30: 'warning--other-danger--g1' 
  31: 'complementary--trucks-turn-right--g1' 
  32: 'complementary--distance--g1' 
  33: 'regulatory--one-way-left--g3' 
  34: 'regulatory--no-right-turn--g1' 
  35: 'warning--railroad-crossing--g1' 
  36: 'regulatory--one-way-left--g1' 
  37: 'complementary--maximum-speed-limit-35--g1' 
  38: 'warning--double-curve-first-right--g2' 
  39: 'complementary--chevron-left--g2' 
  40: 'regulatory--dual-lanes-turn-left-or-straight--g1' 
  41: 'regulatory--keep-right--g4' 
  42: 'regulatory--yield--g1' 
  43: 'regulatory--left-turn-yield-on-green--g1' 
  44: 'regulatory--maximum-speed-limit-100--g3' 
  45: 'warning--road-bump--g2' 
  46: 'regulatory--no-parking--g5' 
  47: 'warning--traffic-signals--g2' 
  48: 'warning--road-narrows--g1' 
  49: 'information--pedestrians-crossing--g1' 
  50: 'complementary--tow-away-zone--g1' 
  51: 'warning--turn-right--g1' 
  52: 'complementary--maximum-speed-limit-15--g1' 
  53: 'complementary--keep-left--g1' 
  54: 'regulatory--one-way-right--g3' 
  55: 'warning--school-zone--g2' 
  56: 'complementary--keep-right--g1' 
  57: 'regulatory--go-straight-or-turn-right--g1' 
  58: 'information--bus-stop--g1' 
  59: 'regulatory--no-entry--g1' 
  60: 'warning--railroad-crossing-without-barriers--g4' 
  61: 'regulatory--no-overtaking--g1' 
  62: 'regulatory--go-straight-or-turn-left--g3' 
  63: 'regulatory--pedestrians-only--g1' 
  64: 'regulatory--turn-right-ahead--g1' 
  65: 'information--tram-bus-stop--g2' 
  66: 'warning--height-restriction--g2' 
  67: 'regulatory--turn-left--g1' 
  68: 'regulatory--go-straight--g1' 
  69: 'regulatory--maximum-speed-limit-25--g2' 
  70: 'warning--pedestrians-crossing--g4' 
  71: 'warning--crossroads--g3' 
  72: 'warning--other-danger--g3' 
  73: 'warning--crossroads--g1' 
  74: 'regulatory--maximum-speed-limit-90--g1' 
  75: 'warning--railroad-crossing-without-barriers--g3' 
  76: 'warning--texts--g1' 
  77: 'complementary--distance--g3' 
  78: 'complementary--chevron-left--g1' 
  79: 'warning--curve-right--g1' 
  80: 'regulatory--maximum-speed-limit-40--g1' 
  81: 'warning--junction-with-a-side-road-perpendicular-right--g1' 
  82: 'warning--narrow-bridge--g1' 
  83: 'information--disabled-persons--g1' 
  84: 'information--parking--g1' 
  85: 'regulatory--no-heavy-goods-vehicles--g4' 
  86: 'complementary--go-right--g1' 
  87: 'regulatory--no-heavy-goods-vehicles--g1' 
  88: 'regulatory--road-closed-to-vehicles--g3' 
  89: 'warning--railroad-crossing-with-barriers--g4' 
  90: 'regulatory--shared-path-pedestrians-and-bicycles--g1' 
  91: 'regulatory--roundabout--g1' 
  92: 'complementary--chevron-right--g1' 
  93: 'warning--traffic-signals--g1' 
  94: 'regulatory--no-parking--g1' 
  95: 'complementary--distance--g2' 
  96: 'warning--road-bump--g1' 
  97: 'regulatory--no-u-turn--g1' 
  98: 'warning--texts--g2' 
  99: 'regulatory--maximum-speed-limit-25--g1' 
  100: 'regulatory--height-limit--g1' 
  101: 'regulatory--no-left-turn--g1' 
  102: 'regulatory--pass-on-either-side--g1' 
  103: 'warning--curve-left--g2' 
  104: 'warning--slippery-road-surface--g2' 
  105: 'warning--children--g2' 
  106: 'regulatory--maximum-speed-limit-50--g1' 
  107: 'regulatory--maximum-speed-limit-60--g1' 
  108: 'regulatory--turn-right--g1' 
  109: 'regulatory--no-parking-or-no-stopping--g1' 
  110: 'regulatory--roundabout--g2' 
  111: 'warning--roadworks--g6' 
  112: 'regulatory--maximum-speed-limit-45--g1' 
  113: 'regulatory--no-mopeds-or-bicycles--g1' 
  114: 'complementary--obstacle-delineator--g1' 
  115: 'regulatory--no-overtaking--g5' 
  116: 'information--gas-station--g3' 
  117: 'warning--curve-left--g1' 
  118: 'complementary--chevron-left--g4' 
  119: 'complementary--chevron-left--g3' 
  120: 'warning--roadworks--g1' 
  121: 'warning--road-narrows-left--g1' 
  122: 'regulatory--no-buses--g3' 
  123: 'warning--road-narrows-right--g1' 
  124: 'warning--slippery-road-surface--g1' 
  125: 'regulatory--no-bicycles--g3' 
  126: 'regulatory--no-stopping--g2' 
  127: 'regulatory--maximum-speed-limit-35--g2' 
  128: 'regulatory--no-parking--g2' 
  129: 'warning--dip--g2' 
  130: 'complementary--chevron-right--g5' 
  131: 'warning--pedestrians-crossing--g1' 
  132: 'regulatory--stop--g10' 
  133: 'regulatory--bicycles-only--g2' 
  134: 'complementary--go-left--g1' 
  135: 'complementary--maximum-speed-limit-45--g1' 
  136: 'warning--curve-right--g2' 
  137: 'information--hospital--g1' 
  138: 'regulatory--keep-left--g1' 
  139: 'warning--hairpin-curve-left--g3' 
  140: 'warning--flaggers-in-road--g1' 
  141: 'warning--traffic-merges-right--g2' 
  142: 'information--motorway--g1' 
  143: 'warning--stop-ahead--g9' 
  144: 'regulatory--pass-on-either-side--g2' 
  145: 'warning--trail-crossing--g2' 
  146: 'information--children--g1' 
  147: 'regulatory--end-of-speed-limit-zone--g1' 
  148: 'warning--bicycles-crossing--g1' 
  149: 'complementary--extent-of-prohibition-area-both-direction--g1' 
  150: 'regulatory--no-left-turn--g2' 
  151: 'warning--divided-highway-ends--g2' 
  152: 'regulatory--go-straight-or-turn-right--g3' 
  153: 'regulatory--maximum-speed-limit-led-60--g1' 
  154: 'warning--wild-animals--g1' 
  155: 'regulatory--no-vehicles-carrying-dangerous-goods--g1' 
  156: 'regulatory--maximum-speed-limit-120--g1' 
  157: 'regulatory--end-of-prohibition--g1' 
  158: 'complementary--one-direction-left--g1' 
  159: 'information--highway-exit--g1' 
  160: 'regulatory--turn-right--g2' 
  161: 'regulatory--no-hawkers--g1' 
  162: 'regulatory--no-bicycles--g2' 
  163: 'information--minimum-speed-40--g1' 
  164: 'complementary--go-right--g2' 
  165: 'complementary--maximum-speed-limit-30--g1' 
  166: 'warning--children--g1' 
  167: 'regulatory--end-of-buses-only--g1' 
  168: 'regulatory--end-of-bicycles-only--g1' 
  169: 'regulatory--buses-only--g1' 
  170: 'warning--hairpin-curve-left--g1' 
  171: 'warning--falling-rocks-or-debris-right--g2' 
  172: 'regulatory--one-way-right--g2' 
  173: 'regulatory--go-straight-or-turn-left--g1' 
  174: 'warning--narrow-bridge--g3' 
  175: 'regulatory--weight-limit--g1' 
  176: 'regulatory--maximum-speed-limit-70--g1' 
  177: 'regulatory--one-way-right--g1' 
  178: 'regulatory--no-motor-vehicles-except-motorcycles--g2' 
  179: 'information--interstate-route--g1' 
  180: 'warning--junction-with-a-side-road-perpendicular-left--g1' 
  181: 'regulatory--no-overtaking--g4' 
  182: 'complementary--turn-left--g2' 
  183: 'regulatory--one-way-straight--g1' 
  184: 'information--airport--g1' 
  185: 'regulatory--dual-lanes-go-straight-on-left--g1' 
  186: 'regulatory--pedestrians-only--g2' 
  187: 'information--telephone--g2' 
  188: 'complementary--maximum-speed-limit-20--g1' 
  189: 'warning--double-turn-first-right--g1' 
  190: 'complementary--chevron-right--g4' 
  191: 'regulatory--no-overtaking-by-heavy-goods-vehicles--g1' 
  192: 'regulatory--maximum-speed-limit-100--g1' 
  193: 'warning--falling-rocks-or-debris-right--g1' 
  194: 'warning--bus-stop-ahead--g3' 
  195: 'warning--road-narrows-right--g2' 
  196: 'information--dead-end--g1' 
  197: 'regulatory--radar-enforced--g1' 
  198: 'warning--roadworks--g3' 
  199: 'regulatory--keep-left--g2' 
  200: 'regulatory--bicycles-only--g3' 
  201: 'regulatory--stop-here-on-red-or-flashing-light--g1' 
  202: 'regulatory--no-parking-or-no-stopping--g2' 
  203: 'warning--dual-lanes-right-turn-or-go-straight--g1' 
  204: 'warning--railroad-crossing-with-barriers--g2' 
  205: 'warning--road-narrows--g2' 
  206: 'regulatory--maximum-speed-limit-40--g3' 
  207: 'warning--hairpin-curve-right--g1' 
  208: 'regulatory--maximum-speed-limit-30--g3' 
  209: 'information--bike-route--g1' 
  210: 'regulatory--no-motorcycles--g1' 
  211: 'regulatory--no-pedestrians--g1' 
  212: 'regulatory--no-right-turn--g2' 
  213: 'regulatory--no-parking-or-no-stopping--g3' 
  214: 'warning--roundabout--g1' 
  215: 'regulatory--reversible-lanes--g2' 
  216: 'regulatory--no-overtaking--g2' 
  217: 'warning--railroad-intersection--g3' 
  218: 'warning--traffic-signals--g3' 
  219: 'regulatory--no-pedestrians--g2' 
  220: 'regulatory--maximum-speed-limit-55--g2' 
  221: 'complementary--chevron-right--g3' 
  222: 'information--end-of-living-street--g1' 
  223: 'regulatory--maximum-speed-limit-5--g1' 
  224: 'warning--slippery-motorcycles--g1' 
  225: 'warning--winding-road-first-left--g2' 
  226: 'complementary--maximum-speed-limit-75--g1' 
  227: 'regulatory--turn-right--g3' 
  228: 'warning--pedestrian-stumble-train--g1' 
  229: 'regulatory--priority-over-oncoming-vehicles--g1' 
  230: 'complementary--buses--g1' 
  231: 'regulatory--maximum-speed-limit-20--g1' 
  232: 'regulatory--end-of-maximum-speed-limit-70--g2' 
  233: 'regulatory--one-way-left--g2' 
  234: 'regulatory--dual-lanes-turn-left-no-u-turn--g1' 
  235: 'warning--double-curve-first-right--g1' 
  236: 'information--end-of-motorway--g1' 
  237: 'regulatory--text-four-lines--g1' 
  238: 'complementary--trucks--g1' 
  239: 'regulatory--passing-lane-ahead--g1' 
  240: 'warning--pass-left-or-right--g2' 
  241: 'complementary--except-bicycles--g1' 
  242: 'warning--texts--g3' 
  243: 'information--telephone--g1' 
  244: 'regulatory--no-turn-on-red--g3' 
  245: 'warning--traffic-merges-left--g1' 
  246: 'regulatory--no-motor-vehicles-except-motorcycles--g1' 
  247: 'regulatory--mopeds-and-bicycles-only--g1' 
  248: 'regulatory--u-turn--g1' 
  249: 'warning--turn-left--g1' 
  250: 'complementary--one-direction-right--g1' 
  251: 'warning--railroad-crossing-with-barriers--g1' 
  252: 'warning--railroad-intersection--g4' 
  253: 'regulatory--road-closed--g2' 
  254: 'warning--pedestrians-crossing--g10' 
  255: 'warning--double-reverse-curve-right--g1' 
  256: 'regulatory--no-stopping--g5' 
  257: 'regulatory--no-motorcycles--g2' 
  258: 'complementary--accident-area--g3' 
  259: 'complementary--chevron-left--g5' 
  260: 'complementary--maximum-speed-limit-50--g1' 
  261: 'regulatory--turn-right-ahead--g2' 
  262: 'warning--wild-animals--g4' 
  263: 'information--camp--g1' 
  264: 'warning--emergency-vehicles--g1' 
  265: 'warning--t-roads--g1' 
  266: 'warning--uneven-road--g6' 
  267: 'information--trailer-camping--g1' 
  268: 'warning--road-narrows-left--g2' 
  269: 'information--road-bump--g1' 
  270: 'complementary--priority-route-at-intersection--g1' 
  271: 'regulatory--no-stopping--g4' 
  272: 'regulatory--do-not-block-intersection--g1' 
  273: 'regulatory--no-heavy-goods-vehicles--g5' 
  274: 'warning--winding-road-first-right--g1' 
  275: 'regulatory--no-turn-on-red--g1' 
  276: 'regulatory--no-u-turn--g3' 
  277: 'warning--loop-270-degree--g1' 
  278: 'warning--double-curve-first-left--g1' 
  279: 'complementary--pass-right--g1' 
  280: 'warning--junction-with-a-side-road-perpendicular-right--g3' 
  281: 'warning--trucks-crossing--g1' 
  282: 'information--parking--g45' 
  283: 'warning--pass-left-or-right--g1' 
  284: 'warning--added-lane-right--g1' 
  285: 'regulatory--stop--g2' 
  286: 'information--food--g2' 
  287: 'regulatory--triple-lanes-turn-left-center-lane--g1' 
  288: 'complementary--chevron-right-unsure--g6' 
  289: 'warning--domestic-animals--g3' 
  290: 'regulatory--turning-vehicles-yield-to-pedestrians--g1' 
  291: 'regulatory--turn-left--g2' 
  292: 'regulatory--no-turn-on-red--g2' 
  293: 'regulatory--maximum-speed-limit-10--g1' 
  294: 'regulatory--no-u-turn--g2' 
  295: 'regulatory--keep-right--g2' 
  296: 'regulatory--no-straight-through--g1' 
  297: 'regulatory--width-limit--g1' 
  298: 'regulatory--maximum-speed-limit-110--g1' 
  299: 'information--living-street--g1' 
  300: 'information--end-of-limited-access-road--g1' 
  301: 'warning--trams-crossing--g1' 
  302: 'information--end-of-built-up-area--g1' 
  303: 'warning--winding-road-first-left--g1' 
  304: 'warning--hairpin-curve-right--g4' 
  305: 'regulatory--no-motor-vehicles--g4' 
  306: 'regulatory--turn-left-ahead--g1' 
  307: 'warning--two-way-traffic--g2' 
  308: 'warning--two-way-traffic--g1' 
  309: 'regulatory--end-of-priority-road--g1' 
  310: 'warning--divided-highway-ends--g1' 
  311: 'information--safety-area--g2' 
  312: 'warning--t-roads--g2' 
  313: 'regulatory--shared-path-bicycles-and-pedestrians--g1' 
  314: 'regulatory--maximum-speed-limit-15--g1' 
  315: 'regulatory--no-motor-vehicle-trailers--g1' 
  316: 'regulatory--dual-path-pedestrians-and-bicycles--g1' 
  317: 'regulatory--maximum-speed-limit-50--g6' 
  318: 'regulatory--no-straight-through--g2' 
  319: 'regulatory--lane-control--g1' 
  320: 'regulatory--turn-left--g3' 
  321: 'warning--steep-ascent--g7' 
  322: 'warning--railroad-crossing--g3' 
  323: 'complementary--maximum-speed-limit-25--g1' 
  324: 'information--parking--g6' 
  325: 'warning--road-widens-right--g1' 
  326: 'regulatory--no-left-turn--g3' 
  327: 'regulatory--no-stopping--g8' 
  328: 'regulatory--go-straight-or-turn-left--g2' 
  329: 'warning--horizontal-alignment-right--g1' 
  330: 'information--parking--g2' 
  331: 'information--parking--g5' 
  332: 'complementary--maximum-speed-limit-40--g1' 
  333: 'complementary--maximum-speed-limit-55--g1' 
  334: 'warning--double-curve-first-left--g2' 
  335: 'warning--playground--g1' 
  336: 'complementary--maximum-speed-limit-70--g1' 
  337: 'warning--uneven-road--g2' 
  338: 'complementary--both-directions--g1' 
  339: 'warning--junction-with-a-side-road-acute-left--g1' 
  340: 'warning--pedestrians-crossing--g5' 
  341: 'regulatory--maximum-speed-limit-led-80--g1' 
  342: 'warning--uneven-roads-ahead--g1' 
  343: 'warning--turn-right--g2' 
  344: 'warning--accidental-area-unsure--g2' 
  345: 'complementary--turn-right--g2' 
  346: 'regulatory--dual-path-bicycles-and-pedestrians--g1' 
  347: 'regulatory--dual-lanes-go-straight-on-right--g1' 
  348: 'warning--traffic-signals--g4' 
  349: 'regulatory--end-of-maximum-speed-limit-30--g2' 
  350: 'regulatory--maximum-speed-limit-led-100--g1' 
  351: 'regulatory--no-turns--g1' 
  352: 'warning--y-roads--g1' 
  353: 'regulatory--stop-here-on-red-or-flashing-light--g2' 
  354: 'warning--winding-road-first-right--g3' 
  355: 'regulatory--end-of-no-parking--g1' 
  356: 'warning--bicycles-crossing--g2' 
  357: 'information--emergency-facility--g2' 
  358: 'warning--horizontal-alignment-right--g3' 
  359: 'regulatory--minimum-safe-distance--g1' 
  360: 'warning--offset-roads--g3' 
  361: 'regulatory--stop-signals--g1' 
  362: 'regulatory--do-not-stop-on-tracks--g1' 
  363: 'regulatory--no-pedestrians-or-bicycles--g1' 
  364: 'regulatory--detour-left--g1' 
  365: 'regulatory--wrong-way--g1' 
  366: 'regulatory--go-straight--g3' 
  367: 'regulatory--parking-restrictions--g2' 
  368: 'regulatory--no-motor-vehicles--g1' 
  369: 'information--end-of-pedestrians-only--g2' 
  370: 'warning--horizontal-alignment-left--g1' 
  371: 'information--gas-station--g1' 
  372: 'information--lodging--g1' 
  373: 'warning--wombat-crossing--g1' 
  374: 'warning--playground--g3' 
  375: 'regulatory--no-heavy-goods-vehicles-or-buses--g1' 
  376: 'warning--junction-with-a-side-road-perpendicular-left--g4' 
  377: 'warning--bicycles-crossing--g3' 
  378: 'warning--falling-rocks-or-debris-right--g4' 
  379: 'regulatory--maximum-speed-limit-65--g2' 
  380: 'regulatory--road-closed--g1' 
  381: 'regulatory--road-closed-to-vehicles--g1' 
  382: 'regulatory--maximum-speed-limit-40--g6' 
  383: 'regulatory--no-pedestrians--g3' 
  384: 'information--highway-interstate-route--g2' 
  385: 'warning--pedestrians-crossing--g12' 
  386: 'regulatory--dual-lanes-turn-right-or-straight--g1' 
  387: 'warning--pedestrians-crossing--g11' 
  388: 'warning--pedestrians-crossing--g9' 
  389: 'warning--equestrians-crossing--g2' 
  390: 'warning--traffic-merges-left--g2' 
