model : ./configs/nano/yolov8n.pt  # path to model file, i.e. yolov8n.pt, yolov8n.yaml
# model : ./runs/detect/train31/weights/last.pt
data  : ./configs/nano/data.yaml  # path to data file, i.e. coco128.yaml
# project : "./runs/detect/augmented/"

# Basic params
epochs : 50  # number of epochs to train for
batch : 16  # number of images per batch (-1 for AutoBatch)
imgsz : 1280  # size of input images as integer or w,h
single_cls : False  # train multi-class data as single-class
save : True  # save train checkpoints and predict results
patience : 50  # epochs to wait for no observable improvement for early stopping of training
device : 1  # device to run on, i.e. cuda device:0 or device:0,1,2,3 or device:cpu
save_period : 10  # Save checkpoint every x epochs (disabled if < 1)
resume : False  # resume training from last checkpoint
lr0 : 0.01  # initial learning rate (i.e. SGD:1E-2, Adam:1E-3)
lrf : 0.01  # final learning rate (lr0 * lrf)
cache : False  # True/ram, disk or False. Use cache for data loading
warmup_epochs : 3.0  # warmup epochs (fractions ok)
warmup_momentum : 0.8  # warmup initial momentum
warmup_bias_lr : 0.1  # warmup initial bias lr

# Augmentation

scale: 0.3  # image scale (+/- gain) # Original 0.2
shear: 0.2  # image shear (+/- deg) from -0.5 to 0.5
perspective: 0.1  # image perspective (+/- fraction), range 0-0.001 
flipud: 0.7  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 0.3  # image mosaic (probability) # Initially 0.3
mixup: 0.1  # image mixup (probability)
copy_paste: 0.3  # segment copy-paste (probability) # Original 0.0


# # Advanced params
# workers : 8  # number of worker threads for data loading (per RANK if DDP)
# project : None  # project name
name : "1280_exp"  # experiment name
exist_ok : True  # whether to overwrite existing experiment
# pretrained : False  # whether to use a pretrained model
# optimizer : 'auto'  # optimizer to use, choices:[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
# verbose : False  # whether to print verbose output
# seed : 0  # random seed for reproducibility
# deterministic : True  # whether to enable deterministic mode
# rect : False  # rectangular training with each batch collated for minimum padding
# cos_lr : False  # use cosine learning rate scheduler
# close_mosaic : 0  # (int) disable mosaic augmentation for final epochs
# amp : True  # Automatic Mixed Precision (AMP) training, choices:[True, False]
# fraction : 1.0  # dataset fraction to train on (default is 1.0, all images in train set)
# profile : False  # profile ONNX and TensorRT speeds during training for loggers
# momentum : 0.937  # SGD momentum/Adam beta1
# weight_decay : 0.0005  # optimizer weight decay 5e-4
# box : 7.5  # box loss gain
# cls : 0.5  # cls loss gain (scale with pixels)
# dfl : 1.5  # dfl loss gain
# pose : 12.0  # pose loss gain (pose-only)
# kobj : 2.0  # keypoint obj loss gain (pose-only)
# label_smoothing : 0.0  # label smoothing (fraction)
# overlap_mask : True  # masks should overlap during training (segment train only)
# nbs : 64  # nominal batch size
# mask_ratio : 4  # mask downsample ratio (segment train only)
# dropout : 0.0  # use dropout regularization (classify train only)
# val : True  # validate/test
